# Generated by Django 3.2.7 on 2021-11-23 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='failed_to_parse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('uid', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='firm_admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Undefined')])),
            ],
        ),
        migrations.CreateModel(
            name='genderPerNames',
            fields=[
                ('surname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
            ],
        ),
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='firms',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('CHE', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('canton', models.CharField(max_length=10)),
                ('form', models.CharField(choices=[('SA', 'Société anonyme'), ('SARL', 'Société à responsabilité limitée'), ('EI', 'Entreprise individuelle')], max_length=5)),
                ('street', models.CharField(max_length=50)),
                ('zip', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=50)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.firm_admin')),
            ],
        ),
    ]
