# Generated by Django 3.2.7 on 2021-09-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('zip', models.IntegerField(max_length=5)),
            ],
        ),
    ]
