# Generated by Django 3.2.7 on 2021-09-10 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='firms',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='API.address'),
            preserve_default=False,
        ),
    ]
