# Generated by Django 3.2.7 on 2021-09-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_firms_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
