# Generated by Django 3.2.7 on 2021-09-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_address_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='firms',
            name='admin',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firms',
            name='canton',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firms',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
